cloud_topic: /cloud_registered_body
odom_topic: /Odometry
map_frame: map
local_frame: lidar_now
update_hz: 1.0
rough_scan_resolution: 0.25
rough_map_resolution: 0.25
rough_max_iteration: 5
rough_score_thresh: 0.2
x: 0.0
y: 0.0
z: 0.0
roll: 3.14159
pitch: 0.0
yaw: 0.0
pcd_path: "/home/ifr/ifr-ros2/ws-sentry-lib/src/laser_to_foot/pcd_save/map_1745106212195.pcd"
refine_scan_resolution: 0.1
refine_map_resolution: 0.1
refine_max_iteration: 10
refine_score_thresh: 0.1